
### Configurations  ###

## General ##
server:
  port: 8090
spring:
  application:
    name: auth-service
  security:
    user:
      password: KEVENlolo114--
  session:
    store-type: redis
  redis:
    host: localhost
    port: 6379